create table tenant (
  id bigint generated by default as identity primary key,
  name varchar(120) not null default '未命名租户',
  city varchar(80) not null default '',
  status varchar(32) not null default 'trialing',
  trial_start_at timestamptz not null,
  trial_end_at timestamptz not null,
  freeze_reason varchar(500),
  frozen_at timestamptz,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_tenant_status check (status in ('trialing', 'expiring', 'frozen', 'extended')),
  constraint chk_tenant_trial_range check (trial_end_at >= trial_start_at)
);

create table admin_user (
  id bigint generated by default as identity primary key,
  login_name varchar(120) not null unique,
  password_hash varchar(255) not null,
  display_name varchar(120) not null,
  status varchar(32) not null default 'active',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_admin_user_status check (status in ('active', 'disabled'))
);

create table auth_session (
  token_hash char(64) primary key,
  actor_type varchar(32) not null,
  subject_id varchar(128) not null,
  tenant_id bigint references tenant(id),
  created_at timestamptz not null default current_timestamp,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  constraint chk_auth_session_actor check (actor_type in ('admin', 'owner', 'staff', 'member'))
);

create table owner_wechat_identity (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  openid varchar(128) not null unique,
  last_login_at timestamptz not null default current_timestamp,
  trial_notice_acknowledged_at timestamptz,
  created_at timestamptz not null default current_timestamp
);

create table store_onboarding_draft (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  owner_openid varchar(128) not null,
  store_profile_draft jsonb not null default '{}'::jsonb,
  business_hours_draft jsonb not null default '{}'::jsonb,
  resources_draft jsonb not null default '[]'::jsonb,
  completion_status jsonb not null default '{"storeProfileDone":false,"businessHoursDone":false,"resourceDone":false}'::jsonb,
  status varchar(32) not null default 'draft',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_onboarding_tenant unique (tenant_id),
  constraint chk_onboarding_status check (status in ('draft', 'converted'))
);

create table store (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  name varchar(120) not null,
  business_categories jsonb not null,
  service_tags jsonb not null,
  address varchar(255) not null,
  contact_phone varchar(40) not null,
  business_hours jsonb not null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_store_tenant unique (tenant_id)
);

create table resource (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  name varchar(80) not null,
  resource_type varchar(80) not null,
  capacity integer not null,
  enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_resource_capacity check (capacity >= 1),
  constraint uq_resource_name unique (tenant_id, store_id, name)
);

create table staff_account (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  login_name varchar(80) not null,
  password_hash varchar(255) not null,
  staff_name varchar(80) not null,
  role_label varchar(80) not null,
  status varchar(32) not null default 'active',
  first_login boolean not null default true,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_staff_login unique (login_name),
  constraint chk_staff_status check (status in ('active', 'disabled'))
);

create table staff_profile (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  staff_account_id bigint not null references staff_account(id) on delete cascade,
  display_name varchar(80) not null,
  specialty_text varchar(500) not null default '',
  intro_text varchar(1000) not null default '',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_staff_profile unique (staff_account_id)
);

create table service_item (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  name varchar(120) not null,
  service_type varchar(80) not null,
  duration_min integer not null,
  default_capacity integer not null,
  deduct_count integer not null default 1,
  status varchar(32) not null default 'draft',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_service_duration check (duration_min > 0),
  constraint chk_service_capacity check (default_capacity > 0),
  constraint chk_service_deduct check (deduct_count > 0),
  constraint chk_service_status check (status in ('draft', 'active', 'disabled'))
);

create table service_resource_binding (
  tenant_id bigint not null references tenant(id),
  service_item_id bigint not null references service_item(id) on delete cascade,
  resource_id bigint not null references resource(id),
  primary key (service_item_id, resource_id)
);

create table staff_service_binding (
  tenant_id bigint not null references tenant(id),
  staff_account_id bigint not null references staff_account(id),
  service_item_id bigint not null references service_item(id) on delete cascade,
  primary key (staff_account_id, service_item_id)
);

create table card_template (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  name varchar(120) not null,
  card_type varchar(32) not null,
  sale_price_yuan numeric(12,2) not null,
  total_count integer,
  valid_days integer not null,
  low_balance_threshold integer,
  status varchar(32) not null default 'active',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_card_template_type check (card_type in ('count', 'period')),
  constraint chk_card_template_status check (status in ('active', 'disabled')),
  constraint chk_card_template_price check (sale_price_yuan >= 0),
  constraint chk_card_template_valid_days check (valid_days > 0),
  constraint chk_card_template_count check (
    (card_type = 'count' and total_count > 0 and low_balance_threshold >= 0)
    or (card_type = 'period' and total_count is null and low_balance_threshold is null)
  )
);

create table card_template_service_scope (
  tenant_id bigint not null references tenant(id),
  card_template_id bigint not null references card_template(id) on delete cascade,
  service_item_id bigint not null references service_item(id),
  primary key (card_template_id, service_item_id)
);

create table card_template_staff_scope (
  tenant_id bigint not null references tenant(id),
  card_template_id bigint not null references card_template(id) on delete cascade,
  staff_account_id bigint not null references staff_account(id),
  primary key (card_template_id, staff_account_id)
);

create table member (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  name varchar(80) not null,
  member_no varchar(80) not null,
  contact_text varchar(120) not null default '',
  bind_status varchar(32) not null default 'unbound',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_member_no unique (tenant_id, store_id, member_no),
  constraint chk_member_bind_status check (bind_status in ('unbound', 'bound'))
);

create table member_wechat_identity (
  id bigint generated by default as identity primary key,
  tenant_id bigint references tenant(id),
  openid varchar(128) not null unique,
  member_id bigint references member(id),
  last_login_at timestamptz not null default current_timestamp,
  created_at timestamptz not null default current_timestamp,
  constraint uq_member_identity_member unique (member_id)
);

create table member_invite_code (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  member_id bigint not null references member(id),
  code_hash char(64) not null unique,
  display_code_tail varchar(16) not null,
  status varchar(32) not null default 'active',
  expires_at timestamptz not null,
  bound_openid varchar(128),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_invite_status check (status in ('active', 'used', 'expired', 'revoked'))
);

create table member_card (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  member_id bigint not null references member(id),
  template_id bigint not null references card_template(id),
  card_type varchar(32) not null,
  sale_price_yuan numeric(12,2) not null,
  remain_count integer,
  valid_from date not null,
  valid_until date not null,
  base_status varchar(32) not null default 'active',
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_member_card_type check (card_type in ('count', 'period')),
  constraint chk_member_card_base_status check (base_status in ('active', 'suspended')),
  constraint chk_member_card_price check (sale_price_yuan >= 0),
  constraint chk_member_card_balance check (
    (card_type = 'count' and remain_count >= 0) or (card_type = 'period' and remain_count is null)
  ),
  constraint chk_member_card_range check (valid_until >= valid_from)
);

create table offline_sale_record (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  member_id bigint not null references member(id),
  member_card_id bigint not null references member_card(id),
  sale_amount_yuan numeric(12,2) not null,
  sale_date date not null,
  pay_method_label varchar(40) not null,
  operator_type varchar(32) not null,
  operator_id varchar(80) not null,
  created_at timestamptz not null default current_timestamp,
  constraint uq_sale_member_card unique (member_card_id),
  constraint chk_sale_amount check (sale_amount_yuan >= 0),
  constraint chk_sale_operator check (operator_type in ('owner', 'admin'))
);

create table bookable_slot (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  service_item_id bigint not null references service_item(id),
  staff_account_id bigint not null references staff_account(id),
  resource_id bigint not null references resource(id),
  start_at timestamptz not null,
  end_at timestamptz not null,
  capacity integer not null,
  reserved_count integer not null default 0,
  status varchar(32) not null default 'draft',
  cancel_deadline_min integer not null,
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_slot_status check (status in ('draft', 'published', 'cancelled', 'disabled')),
  constraint chk_slot_range check (end_at > start_at),
  constraint chk_slot_capacity check (capacity > 0 and reserved_count >= 0 and reserved_count <= capacity),
  constraint chk_slot_cancel_deadline check (cancel_deadline_min >= 0)
);

create table booking (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  bookable_slot_id bigint not null references bookable_slot(id),
  member_id bigint not null references member(id),
  member_card_id bigint not null references member_card(id),
  status varchar(32) not null default 'reserved',
  reserved_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_booking_status check (status in ('reserved', 'cancelled', 'arrived', 'deducted', 'note_done'))
);

create unique index uq_booking_active_member_slot on booking(bookable_slot_id, member_id)
  where status in ('reserved', 'arrived', 'deducted', 'note_done');

create table booking_waitlist (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  bookable_slot_id bigint not null references bookable_slot(id),
  member_id bigint not null references member(id),
  status varchar(32) not null default 'waiting',
  created_at timestamptz not null default current_timestamp,
  constraint chk_waitlist_status check (status in ('waiting', 'cancelled'))
);

create unique index uq_waitlist_active_member_slot on booking_waitlist(bookable_slot_id, member_id)
  where status = 'waiting';

create table booking_cancel_record (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  booking_id bigint not null references booking(id),
  cancelled_by_type varchar(32) not null,
  cancelled_by_id varchar(80) not null,
  reason_text varchar(500),
  created_at timestamptz not null default current_timestamp,
  constraint uq_booking_cancel unique (booking_id),
  constraint chk_booking_cancel_actor check (cancelled_by_type in ('member', 'owner', 'system'))
);

create table attendance_confirm (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  booking_id bigint not null references booking(id),
  member_id bigint not null references member(id),
  member_card_id bigint not null references member_card(id),
  confirmed_by_staff_id bigint not null references staff_account(id),
  confirmed_at timestamptz not null default current_timestamp,
  constraint uq_attendance_booking unique (booking_id)
);

create table deduction_record (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  store_id bigint not null references store(id),
  booking_id bigint not null references booking(id),
  attendance_id bigint not null references attendance_confirm(id),
  member_id bigint not null references member(id),
  member_card_id bigint not null references member_card(id),
  deduct_count integer not null,
  before_count integer,
  after_count integer,
  deducted_by_staff_id bigint not null references staff_account(id),
  deducted_at timestamptz not null default current_timestamp,
  constraint uq_deduction_booking unique (booking_id),
  constraint chk_deduction_count check (deduct_count > 0)
);

create table service_note (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  booking_id bigint not null references booking(id),
  deduction_record_id bigint not null references deduction_record(id),
  staff_note_text varchar(1000),
  member_feedback_text varchar(1000),
  created_at timestamptz not null default current_timestamp,
  updated_at timestamptz not null default current_timestamp,
  constraint uq_service_note_booking unique (booking_id)
);

create table support_wechat (
  id bigint generated by default as identity primary key,
  tenant_id bigint references tenant(id),
  wechat_id varchar(120) not null,
  display_text varchar(500) not null,
  display_scope varchar(500) not null,
  enabled boolean not null default true,
  updated_at timestamptz not null default current_timestamp
);

create unique index uq_support_wechat_default on support_wechat ((tenant_id is null)) where tenant_id is null;
create unique index uq_support_wechat_tenant on support_wechat (tenant_id) where tenant_id is not null;

create table platform_config (
  config_key varchar(120) primary key,
  name varchar(120) not null,
  value_text varchar(255) not null,
  value_type varchar(32) not null,
  unit varchar(32) not null default '',
  min_value integer,
  max_value integer,
  impact_scope varchar(500) not null,
  editable boolean not null default true,
  enabled boolean not null default true,
  updated_at timestamptz not null default current_timestamp,
  constraint chk_platform_config_type check (value_type in ('integer', 'string', 'boolean'))
);

create table audit_log (
  id bigint generated by default as identity primary key,
  tenant_id bigint references tenant(id),
  actor_type varchar(32) not null,
  actor_name varchar(120) not null,
  action varchar(80) not null,
  target_name varchar(160) not null,
  old_value varchar(500),
  new_value varchar(500),
  before_data jsonb,
  after_data jsonb,
  reason varchar(500),
  created_at timestamptz not null default current_timestamp,
  constraint chk_audit_actor_type check (actor_type in ('admin', 'owner', 'staff', 'member', 'system'))
);

create table idempotency_request (
  id bigint generated by default as identity primary key,
  actor_type varchar(32) not null,
  actor_id varchar(128) not null,
  operation varchar(120) not null,
  idempotency_key varchar(120) not null,
  request_hash char(64) not null,
  response_status integer,
  response_body jsonb,
  created_at timestamptz not null default current_timestamp,
  expires_at timestamptz not null,
  constraint uq_idempotency_actor_operation unique (actor_type, actor_id, operation, idempotency_key)
);

create index idx_auth_session_subject on auth_session(actor_type, subject_id, expires_at);
create index idx_auth_session_tenant on auth_session(tenant_id, expires_at);
create index idx_tenant_status_end on tenant(status, trial_end_at);
create index idx_resource_store_enabled on resource(tenant_id, store_id, enabled);
create index idx_service_store_status on service_item(tenant_id, store_id, status);
create index idx_member_store_bind on member(tenant_id, store_id, bind_status);
create index idx_member_card_member on member_card(tenant_id, store_id, member_id, base_status);
create index idx_member_card_warning on member_card(tenant_id, valid_until, remain_count);
create index idx_slot_staff_time on bookable_slot(tenant_id, staff_account_id, start_at);
create index idx_slot_resource_time on bookable_slot(tenant_id, resource_id, start_at);
create index idx_booking_member_time on booking(tenant_id, member_id, reserved_at);
create index idx_booking_slot_status on booking(bookable_slot_id, status);
create index idx_sale_store_date on offline_sale_record(tenant_id, store_id, sale_date);
create index idx_deduction_store_time on deduction_record(tenant_id, store_id, deducted_at);
create index idx_audit_tenant_time on audit_log(tenant_id, created_at desc);
create index idx_audit_action_time on audit_log(action, created_at desc);

insert into support_wechat(tenant_id, wechat_id, display_text, display_scope, enabled)
values (null, 'SerenMeet-CS', '添加客服后，由平台人工调整使用期限并解冻。', '店长冻结页展示客服微信；员工和会员端提示联系门店。', true);

insert into platform_config(config_key, name, value_text, value_type, unit, min_value, max_value, impact_scope)
values
  ('tenant.trial.default_days', '新租户默认试用天数', '30', 'integer', '天', 1, 180, '之后自动开通租户'),
  ('tenant.trial.expiring_warn_days', '租户即将到期提醒', '7', 'integer', '天', 1, 60, '之后状态扫描'),
  ('member.invite.default_valid_days', '邀请码默认有效天数', '7', 'integer', '天', 1, 90, '之后新邀请码'),
  ('booking.cancel.default_deadline_min', '默认取消截止', '120', 'integer', '分钟', 0, 1440, '之后新时段'),
  ('member_card.expiring_warn_days', '会员卡到期提醒', '14', 'integer', '天', 1, 180, '之后报表提醒');
