create table admin_user (
  id bigint generated by default as identity primary key,
  username varchar(120) not null unique,
  password_hash varchar(160) not null,
  display_name varchar(120) not null,
  enabled boolean not null default true,
  created_at timestamp not null default current_timestamp
);

create table admin_session (
  token varchar(120) primary key,
  admin_user_id bigint not null references admin_user(id),
  created_at timestamp not null default current_timestamp,
  expires_at timestamp not null
);

create table tenant (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  city varchar(80) not null,
  status varchar(32) not null,
  trial_start_at date not null,
  trial_end_at date not null,
  frozen_reason varchar(500),
  support_wechat_id varchar(120),
  created_at timestamp not null default current_timestamp,
  updated_at timestamp not null default current_timestamp,
  constraint chk_tenant_status check (status in ('TRIALING', 'EXPIRING', 'FROZEN', 'EXTENDED'))
);

create table store (
  id bigint generated by default as identity primary key,
  tenant_id bigint not null references tenant(id),
  name varchar(120) not null,
  business_categories varchar(300) not null,
  service_tags varchar(500) not null,
  address varchar(500) not null,
  contact_phone varchar(80) not null,
  business_hours varchar(300) not null,
  constraint uq_store_tenant unique (tenant_id)
);

create table tenant_business_snapshot (
  tenant_id bigint primary key references tenant(id),
  issued_cards int not null default 0,
  checkins int not null default 0,
  deductions int not null default 0,
  warning_count int not null default 0,
  low_balance_count int not null default 0,
  expiring_count int not null default 0,
  monthly_sales_yuan numeric(12, 2) not null default 0,
  last_activity_at timestamp
);

create table support_wechat (
  id bigint generated by default as identity primary key,
  tenant_id bigint,
  wechat_id varchar(120) not null,
  display_text varchar(500) not null,
  display_scope varchar(500) not null,
  enabled boolean not null default true,
  updated_at timestamp not null default current_timestamp
);

create table platform_config (
  config_key varchar(120) primary key,
  name varchar(120) not null,
  value_text varchar(120) not null,
  value_type varchar(32) not null,
  unit varchar(32) not null,
  min_value int,
  max_value int,
  impact_scope varchar(500) not null,
  editable boolean not null default true,
  enabled boolean not null default true,
  updated_at timestamp not null default current_timestamp,
  constraint chk_platform_config_value_type check (value_type in ('INTEGER'))
);

create table audit_log (
  id bigint generated by default as identity primary key,
  tenant_id bigint,
  actor_type varchar(32) not null,
  actor_name varchar(120) not null,
  action varchar(80) not null,
  target_name varchar(160) not null,
  old_value varchar(500),
  new_value varchar(500),
  reason varchar(500),
  created_at timestamp not null default current_timestamp,
  constraint chk_audit_actor_type check (actor_type in ('admin', 'system')),
  constraint chk_audit_action check (action in (
    'AUTO_TRIAL_CREATED',
    'FREEZE_TENANT',
    'EXTEND_TRIAL',
    'UPDATE_SUPPORT_WECHAT',
    'UPDATE_CONFIG'
  ))
);

create index idx_admin_session_user on admin_session(admin_user_id, expires_at);
create index idx_tenant_status_end on tenant(status, trial_end_at);
create index idx_tenant_name on tenant(name);
create index idx_audit_tenant_time on audit_log(tenant_id, created_at);
create index idx_audit_action_time on audit_log(action, created_at);

create unique index uq_support_wechat_default
  on support_wechat ((tenant_id is null))
  where tenant_id is null;

insert into admin_user(username, password_hash, display_name, enabled)
values
  ('admin@serenmeet', 'pbkdf2_sha256$120000$fc706504eb8ff12a7383fa3664270fb9$0684a2f219e33ea1dd4402570005f33904ac055986db340336d5e9bbce208a2f', '平台管理员', true);

insert into support_wechat(tenant_id, wechat_id, display_text, display_scope, enabled, updated_at)
values
  (null, 'SerenMeet-CS', '添加客服后，由平台人工调整使用期限并解冻。', '店长冻结页展示客服微信；教练和会员端提示联系门店。', true, timestamp '2026-05-30 17:06:00');

insert into platform_config(config_key, name, value_text, value_type, unit, min_value, max_value, impact_scope, editable, enabled)
values
  ('tenant.trial.default_days', '新租户默认试用天数', '30', 'INTEGER', '天', 1, 180, '之后自动开通租户', true, true),
  ('tenant.trial.expiring_warn_days', '租户即将到期提醒', '7', 'INTEGER', '天', 1, 60, '之后状态扫描', true, true),
  ('member.invite.default_valid_days', '邀请码默认有效天数', '7', 'INTEGER', '天', 1, 90, '之后新邀请码', true, true),
  ('booking.cancel.default_deadline_min', '默认取消截止', '120', 'INTEGER', '分钟', 0, 1440, '之后新时段', true, true),
  ('member_card.expiring_warn_days', '会员卡到期提醒', '14', 'INTEGER', '天', 1, 180, '之后报表提醒', true, true);
